services: 
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cf-admin
      POSTGRES_PASSWORD: cf-db-auth
      POSTGRES_DB: cf-db
    ports:
      - 5432:5432
    volumes:
      - cfdata:/var/lib/postgresql/data
  
volumes:
  cfdata: